bases:  
  - ../bases/repos.yaml
  - ../bases/environments.yaml

{{ readFile "../bases/templates.yaml" }}

commonLabels:
  component: backup

releases:

  - name: kassio-backup-s3
    <<: *release
    chart: minio/minio
    version: 3.6.2
    labels:
      element: s3

  - name: kassio-backup-tool
    <<: *release
    chart: vmware-tanzu/velero
    version: 2.29.1
    labels:
      element: tool
    needs:
      - kassio/kassio-backup-s3