bases:  
  - ../bases/repos.yaml
  - ../bases/environments.yaml

{{ readFile "../bases/templates.yaml" }}

commonLabels:
  component: backup

releases:

  - name: kassio-backup
    <<: *release
    chart: vmware-tanzu/velero
    version: 5.2.2    
    needs:
      - kassio/kassio-storage-s3