bases:
  - ../bases/repos.yaml
  - ../bases/environments.yaml

{{ readFile "../bases/templates.yaml" }}

commonLabels:
  component: backup

releases:

  - name: kassio-backup-data
    <<: *release
    chart: vmware-tanzu/velero
    version: 8.1.0
    labels:
      element: data