bases:  
  - ../bases/repos.yaml
  - ../bases/environments.yaml

{{ readFile "../bases/templates.yaml" }}

commonLabels:
  component: zigbee

releases:
  - name: kassio-zigbee
    <<: *release
    chart: k8s-at-home/zigbee2mqtt
    version: 9.0.1
    needs:
      - kassio/kassio-broker