---
persistence:
  usb:
    hostPath: /dev/ttyACM0
  data:
    storageClass: local-path
    size: 2Gi
config:
  advanced:
    network_key: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    channel: 11 # https://www.metageek.com/training/resources/zigbee-wifi-coexistence.html
ingress:
  main:
    hosts:
      - host: zigbee.kassio
        paths:
          - path: /