apiVersion: v1
description: A Helm chart for kassio
name: kassio
version: 1.0.0-dev
keywords:
  - home-assistant
  - node-red
home: https://github.com/masantiago/kassio
icon:
sources:
  - https://github.com/masantiago/kassio
maintainers:
  - name: masantiago
    email: miguelangel.santiago@hotmail.com
dependencies:
  - name: home-assistant
    version: 11.1.0
    repository: https://k8s-at-home.com/charts/
    condition: home-assistant.enabled
  - name: node-red
    version: 9.0.1
    repository: https://k8s-at-home.com/charts/
    condition: node-red.enabled  
  - name: zigbee2mqtt
    version: 9.0.1
    repository: https://k8s-at-home.com/charts/
    condition: zigbee2mqtt.enabled
  - name: zwave2mqtt
    version: 5.4.0
    repository: https://k8s-at-home.com/charts/
    condition: zwave2mqtt.enabled
  - name: frigate
    version: 6.1.1
    repository: https://k8s-at-home.com/charts/
    condition: frigate.enabled
  - name: kube-prometheus-stack
    alias: monitoring
    version: 20.0.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled
  - name: loki-stack
    alias: logs
    version: 2.4.1
    repository: https://grafana.github.io/helm-charts
    condition: logs.enabled
  - name: network-ups-tools
    alias: sai
    version: 6.0.1
    repository: https://k8s-at-home.com/charts/
    condition: sai.enabled
  - name: adguard-home
    alias: dns
    version: 5.0.3
    repository: https://k8s-at-home.com/charts/
    condition: dns.enabled 
  - name: mosquitto
    version: 4.0.1
    repository: https://k8s-at-home.com/charts/
    condition: mosquitto.enabled
