---
components: 
  ai:
    enabled: false
    stack:
      enabled: true
    proxy:
      enabled: true
  backup:
    platform: intel # intel|arm
    enabled: false    
  broker:
    enabled: true
  db:
    enabled: false
    platform: intel # intel|arm
    frontend:
      enabled: true
    metrics:
      enabled: true
  dns:
    enabled: true  
  engine:
    enabled: true  
  frontend:
    platform: intel # intel|arm
    enabled: true
  monitoring:
    enabled: true
    metrics:
      enabled: true
    logs:
      enabled: true
  storage:
    enabled: false
    platform: intel # intel|arm 
    nas:
      enabled: false
    nfs:
      enabled: false
    s3:
      enabled: false   
  nvr:
    enabled: false
    coral:
      enabled: true
    qsv:
      enabled: true 
  sai:
    enabled: false 
  vault:
    enabled: false    
  zigbee:
    enabled: false
  zwave:
    enabled: false