---
components: 
  ai:
    enabled: false
    stack:
      enabled: false
    proxy:
      enabled: false
    proxy-qsv:
      enabled: false
  backup:
    platform: intel # intel|arm
    enabled: false    
  broker:
    enabled: false
  db:
    enabled: false
    platform: intel # intel|arm
    frontend:
      enabled: false
    metrics:
      enabled: false
  dns:
    enabled: false  
  engine:
    enabled: false  
  frontend:
    platform: intel # intel|arm
    enabled: true
  monitoring:
    enabled: false
    metrics:
      enabled: false
    logs:
      enabled: false
  storage:
    enabled: false
    platform: intel # intel|arm 
    nas:
      enabled: false
    nfs:
      enabled: false
    s3:
      enabled: false   
  nvr:
    enabled: false
    coral:
      enabled: false
    qsv:
      enabled: false 
  sai:
    enabled: false 
  vault:
    enabled: false 
  voice:
    enabled: false
    satellite:
      enabled: false
    tts:
      enabled: false
    asr:
      enabled: false
  zigbee:
    enabled: false
  zwave:
    enabled: false