---
components:
  ai:
    enabled: false
    stack:
      enabled: false
    proxy:
      enabled: false
    proxy-qsv:
      enabled: false
  backup:
    platform: intel # intel|arm
    enabled: false
    data:
      enabled: false
  broker:
    enabled: false
  db:
    enabled: false
    platform: intel # intel|arm
    frontend:
      enabled: false
    frontend-ui:
      enabled: false
    metrics:
      enabled: false
  dns:
    enabled: false
  engine:
    enabled: false
  frontend:
    platform: intel # intel|arm
    enabled: true
  mcp:
    enabled: false
    frontend:
      enabled: false
  monitoring:
    enabled: false
    metrics:
      enabled: false
    logs:
      enabled: false
  storage:
    enabled: false
    platform: intel # intel|arm
    nas:
      enabled: false
    nfs:
      enabled: false
    s3:
      enabled: false
    block:
      enabled: false
  nvr:
    enabled: false
    coral:
      enabled: false
    qsv:
      enabled: false
  sai:
    enabled: false
  ssl:
    enabled: true
    cert:
      enabled: true
    duckdns:
      enabled: false
  vault:
    enabled: false
  voice:
    enabled: false
    satellite:
      enabled: false
    tts:
      enabled: false
    asr:
      enabled: false
  workflow:
    enabled: false
  zigbee:
    enabled: false
  zwave:
    enabled: false
