---
components: 
  backup:
    enabled: false
    s3:
      enabled: true
  broker:
    enabled: true
  db:
    enabled: false
    platform: intel # intel|arm
    frontend:
      enabled: true
    metrics:
      enabled: true
  dns:
    enabled: true  
  engine:
    enabled: true  
  frontend:
    enabled: true
  monitoring:
    enabled: true
    metrics:
      enabled: true
    logs:
      enabled: true
  nas:
    enabled: false
    platform: intel # intel|arm    
  nvr:
    enabled: false
    coral:
      enabled: true
    qsv:
      enabled: true 
  sai:
    enabled: false 
  vault:
    enabled: false    
  zigbee:
    enabled: false
  zwave:
    enabled: false