password: &password <your_password> # Set master password for kassio

home-assistant:
  enabled: true
  image:
    repository: homeassistant/raspberrypi4-homeassistant
    tag: 0.118.5
  hostNetwork: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
  persistence:
    enabled: true
    size: 5Gi
    storageClass: local-path
    accessMode: ReadWriteOnce
      
node-red:
  enabled: true
  image:
    repository: nodered/node-red
    tag: 1.2.6  
  env:
    TZ: Europe/Madrid
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
  persistence:
    data:
      enabled: true
      type: pvc      
      size: 5Gi
      storageClass: local-path
      accessMode: ReadWriteOnce
      mountPath: /data

vernemq:
  enabled: true
  image: 
    repository: timbrand/vernemq-rpi
    tag: 1.10.2  
  persistentVolume:
    enabled: true
    size: 5Gi                
    storageClass: local-path
    accessMode: ReadWriteOnce  
  service:
    type: NodePort
    mqtt:
      nodePort: 32000
  additionalEnv:
    - name: DOCKER_VERNEMQ_USER_ADMIN
      value: *password
    - name: DOCKER_VERNEMQ_USER_HOME-ASSISTANT
      value: *password
    - name: DOCKER_VERNEMQ_USER_NODE-RED
      value: *password
    - name: DOCKER_VERNEMQ_USER_ZWAVE
      value: *password
    - name: DOCKER_VERNEMQ_USER_ZIGBEE
      value: *password
  acl: config/vernemq/vmq.acl
  extraVolumeMounts:
    - name: vernemq-acl
      mountPath: /vernemq/etc/vmq.acl
      subPath: vernemq-acl
      readOnly: true  
  extraVolumes:
    - name: vernemq-acl
      configMap:
        name: kassio-vernemq-acl # Must be first extraVolume

zigbee2mqtt:
  enabled: false  
  image: 
    repository: koenkk/zigbee2mqtt
    tag: 1.17.0
  env:
    TZ: Europe/Madrid 
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
  securityContext:
    privileged: true
  persistence:
    data:
      enabled: true
      type: pvc
      size: 2Gi                
      storageClass: local-path
      accessMode: ReadWriteOnce
      mountPath: /data
    usb:
      enabled: true
      type: hostPath
      hostPath: /dev/ttyACM0
      mountPath: /dev/ttyACM0
  config:
    serial:
      port: /dev/ttyACM0
    homeassistant: true
    mqtt:
      base_topic: zigbee
      server: "mqtt://kassio-vernemq"
      user: zigbee
      password: *password      
    advanced:      
      homeassistant_discovery_topic: "home-assistant"
      homeassistant_status_topic: "home-assistant/status"
      network_key: [4, 1, 10, 4, 2, 14, 3, 6, 8, 8, 13, 11, 2, 9, 7, 15]
      channel: 11 # https://www.metageek.com/training/resources/zigbee-wifi-coexistence.html
    frontend:
      port: 8080
    experimental:
      new_api: true
  nodeSelector:
    kassio/zigbee: "true"

zwave2mqtt:
  enabled: false  
  image:
    repository: robertslando/zwave2mqtt
    tag: 4.1.1
  env:
    TZ: Europe/Madrid  
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
  persistence:
    config:
      enabled: true
      size: 2Gi                
      storageClass: local-path
      accessMode: ReadWriteOnce
  # Path to your zigbee device in the container
  additionalVolumeMounts:
    - name: usb
      mountPath: /dev/ttyACM0
  # Path to your zigbee device on the host
  additionalVolumes:
    - name: usb
      hostPath:
        path: /dev/ttyACM0
  nodeSelector:
    kassio/zwave: "true"

frigate:
  enabled: false  
  image:
    repository: blakeblackshear/frigate
    tag: 0.8.1-aarch64
  timezone: Europe/Madrid
  rtspPassword: *password
  coral:
    enabled: true
    hostPath: /dev/bus/usb
  shmSize: 1Gi # Memory/camera = (width * height * 3 + 270480)/1048576 = <shm size in mb>
  config: |
    mqtt:      
      host: kassio-vernemq
      topic_prefix: "home-assistant/frigate"
      user: home-assistant
      password: '{FRIGATE_RTSP_PASSWORD}'
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
    objects:
      track:
        - person
  nodeSelector:
    kassio/coral: "true"

monitoring:
  enabled: true
  grafana:
    adminPassword: *password
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
    env:
      GF_SECURITY_ALLOW_EMBEDDING: true
  kubeEtcd:
    enabled: false
  prometheus:
    prometheusSpec:
      retention: 15d
      retentionSize: 5GiB
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
            storageClassName: local-path
  alertmanager:
    enabled: false

logs:
  enabled: true    
  loki:
    persistence:
      enabled: true
      storageClassName: local-path
      size: 5Gi  

sai:
  enabled: false
  image:
    repository: ghcr.io/k8s-at-home/network-ups-tools
    tag: v2.7.4-2474-gb4a58380
  env:
    TZ: Europe/Madrid
  securityContext:
    privileged: true
  persistence:
    usb:
      enabled: true
      type: hostPath
      hostPath: /dev/usb
      mountPath: /dev/usb  
  config:
    files:
      nut.conf: |
        MODE=standalone
      upsd.conf: |
        MAXAGE 15
        STATEPATH /var/run/nut
        LISTEN 0.0.0.0 3493
        MAXCONN 1024        
      ups.conf: |
        [salicru]
          driver = blazer_usb
          port = auto
          desc = "SPS ONE 500"
      upsd.users: |
        [admin]
          password = <pwd>
          actions = SET
          instcmds = ALL
      upsmon.conf: |
        MINSUPPLIES 1
  nodeSelector:
    kassio/sai: "true"

dns:
  enabled: true
  image:
    repository: adguard/adguardhome
    tag: v0.106.3
  env:
    TZ: Europe/Madrid
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet  
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
  persistence:
    config:
      enabled: true
      type: pvc
      size: 100Mi
      storageClass: local-path
      accessMode: ReadWriteOnce
      mountPath: /opt/adguardhome/conf
    data:
      enabled: true
      type: pvc
      size: 100Mi
      storageClass: local-path
      accessMode: ReadWriteOnce
      mountPath: /opt/adguardhome/work