bases:  
  - ../bases/repos.yaml
  - ../bases/environments.yaml

{{ readFile "../bases/templates.yaml" }}

commonLabels:
  component: engine

releases:
  - name: kassio-engine
    <<: *release
    chart: k8s-at-home/node-red
    version: 10.3.2