---
ingress:
  main:
    hosts:
      - host: engine.kassio
        paths:
          - path: /
    tls:
      - secretName: kassio-ssl-wildcard-tls
        hosts:
          - engine.kassio
persistence:
  data:
    storageClass: local-path
    size: 5Gi
