---
image:
  repository: nodered/node-red
  tag: 2.1.3  
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
persistence:
  data:
    enabled: true
    type: pvc      
    size: 5Gi
    storageClass: local-path
    accessMode: ReadWriteOnce
    mountPath: /data