---
environmentPath: ".."

components: 
  vault:
    enabled: false
  db:
    enabled: false
    frontend:
      enabled: true
    metrics:
      enabled: true
  engine:
    enabled: true
  broker:
    enabled: true
  zigbee:
    enabled: true
  nvr:
    enabled: false
    coral:
      enabled: true
    qsv:
      enabled: true
  monitoring:
    enabled: true
    metrics:
      enabled: true
    logs:
      enabled: true
  sai:
    enabled: false