---
environmentPath: ".."

components: 
  vault:
    enabled: false
  broker:
    enabled: true
  nvr:
    enabled: true
  monitoring:
    enabled: true
    logs:
      enabled: true
  sai:
    enabled: true