bases:    
  - ../bases/repos.yaml
  - ../bases/environments.yaml

{{ readFile "../bases/templates.yaml" }}

releases:
  - name: kassio-vault    
    <<: *release
    chart: hashicorp/vault
    version: 0.18.0