---
ingress:
  main:
    hosts:
      - host: dns.kassio
        paths:
          - path: /
persistence:
  config:
    storageClass: local-path
    size: 100Mi
  data:
    storageClass: local-path
    size: 100Mi