---
ingress:
  main:
    hosts:
      - host: dns.kassio
        paths:
          - path: /
    tls:
      - secretName: kassio-ssl-wildcard-tls
        hosts:
          - dns.kassio
persistence:
  config:
    storageClass: local-path
    size: 100Mi
  data:
    storageClass: local-path
    size: 100Mi
