bases:  
  - ../bases/repos.yaml
  - ../bases/environments.yaml

{{ readFile "../bases/templates.yaml" }}

commonLabels:
  component: zwave

releases:
  - name: kassio-zwave
    <<: *release
    chart: k8s-at-home/zwavejs2mqtt
    version: 5.3.0
    needs:
      - kassio/kassio-broker