---
ingress:
  main:
    hosts:
      - host: photos.kassio
        paths:
          - path: /
    tls:
      - secretName: kassio-ssl-wildcard-tls
        hosts:
          - photos.kassio
persistence:
  config:
    storageClass: local-path
    size: 5Gi
  originals:
    storageClass: local-path
    size: 5Gi
