bases:  
  - ../bases/repos.yaml
  - ../bases/environments.yaml

{{ readFile "../bases/templates.yaml" }}

commonLabels:
  component: db

releases:

  - name: kassio-db-frontend
    <<: *release
    chart: bitnami/mariadb
    version: 18.2.0
    labels:
      element: frontend

  - name: kassio-db-frontend-ui
    <<: *release
    chart: truecharts/mysql-workbench
    version: 10.0.11
    labels:
      element: frontend-ui

  - name: kassio-db-metrics
    <<: *release
    chart: bitnami/influxdb
    version: 5.3.4
    labels:
      element: metrics