bases:  
  - ../bases/repos.yaml
  - ../bases/environments.yaml

{{ readFile "../bases/templates.yaml" }}

commonLabels:
  component: db

releases:

  - name: kassio-db-frontend
    <<: *release
    chart: bitnami/mariadb
    version: 9.7.0
    labels:
      element: frontend

  - name: kassio-db-metrics
    <<: *release
    chart: bitnami/influxdb
    version: 1.1.9
    labels:
      element: metrics