bases:  
  - ../bases/repos.yaml
  - ../bases/environments.yaml

{{ readFile "../bases/templates.yaml" }}

commonLabels:
  component: frontend

releases:
  - name: kassio-frontend
    <<: *release
    chart: k8s-at-home/home-assistant
    version: 11.1.0