---
ingress:
  main:
    hosts:
      - host: frontend.kassio
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: kassio-ssl-wildcard-tls
        hosts:
          - frontend.kassio
persistence:
  config:
    storageClass: local-path
    size: 5Gi
