bases:  
  - ../bases/repos.yaml
  - ../bases/environments.yaml

{{ readFile "../bases/templates.yaml" }}

commonLabels:
  component: nvr

releases:

  - name: kassio-nvr
    <<: *release
    chart: blakeshome/frigate
    version: 7.8.0
    labels:
      element: coral

  - name: kassio-nvr-qsv
    <<: *release
    chart: blakeshome/frigate
    version: 7.8.0
    labels:
      element: qsv
