bases:  
  - ../bases/repos.yaml
  - ../bases/environments.yaml

{{ readFile "../bases/templates.yaml" }}

commonLabels:
  component: nvr

releases:

  - name: kassio-nvr
    <<: *release
    chart: k8s-at-home/frigate
    version: 8.2.2
    labels:
      element: coral
    needs:
      - kassio/kassio-broker

  - name: kassio-nvr-qsv
    <<: *release
    chart: k8s-at-home/frigate
    version: 8.2.2
    labels:
      element: qsv
    needs:
      - kassio/kassio-broker
  