---
ingress:
  hosts:
    - host: nvr-coral.kassio
      paths:
        - path: /
          pathType: ImplementationSpecific
          portName: http
  tls:
    - secretName: kassio-ssl-wildcard-tls
      hosts:
        - nvr-coral.kassio