---
image:
  repository: blakeblackshear/frigate
  tag: 0.9.4-amd64
service:
  main:
    ports:
      rtmp:
        enabled: true
securityContext:
  privileged: true
persistence:
  cache:
    enabled: true
    type: emptyDir
    medium: Memory
    sizeLimit: 1Gi # Memory/camera = (width * height * 3 + 270480)/1048576 = <shm size in mb>
    mountPath: /dev/shm  
nodeSelector:
  kassio/qsv: "true"