---
config: |
  detectors:
    coral:
      type: edgetpu
      device: usb
  mqtt:      
    host: kassio-broker
    topic_prefix: "home-assistant/nvr"
    user: home-assistant
    password: '{FRIGATE_RTSP_PASSWORD}'
  ffmpeg:
    hwaccel_args:
      - -c:v
      - h264_v4l2m2m
  objects:
    track:
      - person