---
config: |
  mqtt:      
    host: kassio-broker
    topic_prefix: "home-assistant/frigate"
    user: home-assistant
    password: '{FRIGATE_RTSP_PASSWORD}'
    client_id: frigate-qsv
  ffmpeg:
    hwaccel_args:
      - -hwaccel
      - vaapi
      - -hwaccel_device
      - /dev/dri/renderD128
      - -hwaccel_output_format
      - yuv420p
  objects:
    track:
      - person