{{- if .Values.ssl.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "kassio.fullname" . }}-ssl
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ template "kassio.fullname" . }}-ssl-key
    solvers:
    - http01:
       ingress:
         class: traefik
{{- end }}


{{/*
  Useful URLs
  https://www.cloudsavvyit.com/14069/how-to-install-kubernetes-cert-manager-and-configure-lets-encrypt/
  https://cert-manager.io/docs/configuration/acme/dns01/
  https://cert-manager.io/docs/tutorials/acme/ingress/
  https://community.letsencrypt.org/t/intranet-server-urnerror-dns-no-valid-ip-addresses-found/110645/4
  https://letsencrypt.org/docs/challenge-types/
  https://www.reddit.com/r/selfhosted/comments/iq97bx/as_requested_by_the_members_of_this_reddit_i/
  
  https://github.com/vmware-tanzu/sonobuoy
*/}}