{{- if .Values.nfs.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kassio-nfs 
  labels:
    name: kassio-nfs
spec:
  capacity:
    storage: {{ .Values.nfs.size }}
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.server }} 
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kassio-nfs 
spec:
  resources:
    requests:
      storage: {{ .Values.nfs.size }}
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      name: kassio-nfs 
  storageClassName: ""
{{- end }}