bases:  
  - ../bases/repos.yaml
  - ../bases/environments.yaml

{{ readFile "../bases/templates.yaml" }}

commonLabels:
  component: workflow

releases:
  - name: kassio-workflow
    <<: *release
    chart: community-charts/n8n
    version: 1.15.17