---
grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
  nodeSelector:
    kassio/monitoring: "true"
  env:
    GF_SECURITY_ALLOW_EMBEDDING: true
kubeEtcd:
  enabled: false
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: local-path
    nodeSelector:
      kassio/monitoring: "true"
alertmanager:
  enabled: false    
nodeSelector:
  kassio/monitoring: "true"
