---
grafana:
  ingress:
    hosts:
      - monitoring.kassio
prometheus:
  prometheusSpec:
    retention: 15d
    retentionSize: 5GiB
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          resources:
            requests:
              storage: 5Gi