bases:  
  - ../bases/repos.yaml
  - ../bases/environments.yaml

{{ readFile "../bases/templates.yaml" }}

releases:
  - name: kassio-logs
    <<: *release
    chart: grafana/loki-stack
    version: 2.5.0